version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:17.9.1

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  # lint:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Run linters
  #         command: |
  #           yarn lint

  build-publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12
      - run:
          name: Build Docker image
          command: |
            docker build . -t ghcr.io/markormesher/darwin-to-mqtt:$(git describe)
            docker image ls
      - run:
          name: Maybe publish Docker image
          command: |
            # publish tagged commits only
            if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            docker push ghcr.io/markormesher/darwin-to-mqtt:$(git describe)

workflows:
  version: 2
  main:
    jobs:
      - setup
      # - lint:
      #     requires:
      #       - setup
      - build-publish:
          requires:
            - setup
            # - lint
